### ISSUE TITLE
US08 - Como operador, desejo criar e editar um pedido para acompanhar as etapas em que está: orçamento, feedback, negociação, contratação ou execução.

### ISSUE THREAD

**Issue by laragiuliana** [mdsreq-fga-unb/2023.1-Armazenai#4]
Os dados do pedido são:
* Capacidade de produção de soja em sacas
* Capacidade de produção de milho em sacas
* Hectares plantados; Umidade média do grão na colheita
* Área de terreno disponível para a estrutura de armazenagem [US1]
* Valor total negociado; Capacidade de armazenagem do silo
* Capacidade do secador de grãos; Identificador do cliente (CPF/CNPJ)
* Data do pedido

**Comment by kaioenzo** [comment]
# Critérios de aceitação
- [ ] A data dever estar no padrão yyyy-mm-dd
- [ ] Deve ser verificado se o CPF do Cliente já está cadastrado
   - [ ] Caso o cliente não esteja cadastrado, deve abrir uma dialog para cadastrar
