### ISSUE TITLE
US11 - Como operador, desejo realizar buscas de pedidos para facilitar a localização de orçamentos específicos.

### ISSUE THREAD

**Issue by laragiuliana** [mdsreq-fga-unb/2023.1-Armazenai#8]
* Os pedidos podem ser filtrados por:
   - [ ] Identificador do cliente;
   - [ ] Etapa em curso;

* Os pedidos podem ser ordenados por:
   - [ ] Valor do orçamento;
   - [ ] Data de criação;
   - [ ] Data de uma etapa em específico.

**Comment by kaioenzo** [comment]
# Critérios de aceitação
- [ ] O filtro de identificador do cliente deve ser pelo CPF e Nome
- [ ] As datas devem estar no formato yyyy-mm-dd
